import 'package:widgets_flutter/views/ListView/staticList.dart';
import 'package:widgets_flutter/views/appbarView.dart';
import 'package:widgets_flutter/views/buttonView.dart';
import 'package:widgets_flutter/views/cardview/simplecard.dart';
import 'package:widgets_flutter/views/textfield.dart';

const ContainerRoute = '/container/';
const TextRoute = '/text/';
const RowsAndColumnRoute = '/rows/';
const listViewRoute = '/list/';
const staticListRoute = '/static list route/';
const listviewBuilderRoute = '/builder listview/';
const listviewSeperatorRoute = '/seperator listview/';
const cardViewRoute = '/cardview/';
const simpleCardRoute = '/simple card/';
const cardInListRoute = '/list card/';
const imageViewRoute = '/image view/';
const buttonViewRoute = '/button view/';
const textfieldViewRoute = '/textfield/';
const appbarViewRoute = '/appbar/';
