import 'package:flutter/material.dart';
import 'package:widgets_flutter/views/ListView/staticList.dart';
import 'package:widgets_flutter/views/appbarView.dart';
import 'package:widgets_flutter/views/buttonView.dart';
import 'package:widgets_flutter/views/cardview/simplecard.dart';
import 'package:widgets_flutter/views/gestureDetector.dart';
import 'package:widgets_flutter/views/gridView.dart';
import 'package:widgets_flutter/views/popupMenuView.dart';
import 'package:widgets_flutter/views/TabBar/tabBarView.dart';
import 'package:widgets_flutter/views/richText.dart';
import 'package:widgets_flutter/views/textfield.dart';
import 'package:widgets_flutter/views/wrapWidget.dart';

const mainActivityRoute = '/main/';
const ContainerRoute = '/container/';
const TextRoute = '/text/';
const RowsAndColumnRoute = '/rows/';
const listViewRoute = '/list/';
const staticListRoute = '/static list route/';
const listviewBuilderRoute = '/builder listview/';
const listviewSeperatorRoute = '/seperator listview/';
const cardViewRoute = '/cardview/';
const simpleCardRoute = '/simple card/';
const cardInListRoute = '/list card/';
const imageViewRoute = '/image view/';
const buttonViewRoute = '/button view/';
const textfieldViewRoute = '/textfield/';
const appbarViewRoute = '/appbar/';
const BottomNavigationBarRoute = '/bottom navigation/';
const popupMenuViewRoute = '/popup menu/';
const tabBarViewRoute = '/tab bar/';
const dialogRoute = '/dialog/';
const gestureDetectorViewRoute = '/gesture detector/';
const gridViewRoute = '/grid/';
const richTextViewRoute = '/rich text/';
const wrapWidgetViewRoute = '/wrap widget/';
